---
- name: Install and configure Apache HTTPD with a test webpage and health check
  hosts: webservers
  become: yes

  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Ensure httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a test index.html page
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to Apache on Amazon Linux</title>
          </head>
          <body>
              <h1>Hello from Ansible!</h1>
              <p>This page was deployed using Ansible.</p>
          </body>
          </html>
        owner: root
        group: root
        mode: '0644'

    - name: Wait for HTTP service to respond
      uri:
        url: http://{{ inventory_hostname }}
        return_content: yes
        status_code: 200
      register: webpage_response

    - name: Display webpage content
      debug:
        var: webpage_response.content
